### ISSUE TITLE
Quick Start x2 - confusing

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/project-astra#28]
Page: [Set up Google Cloud](https://docs.netapp.com/us-en/project-astra/get-started/set-up-google-cloud.html) has a 'Quick Start', but this section is different to the Project Astra 'Quick Start'.. I think maybe we could just reflect that this page has more comprehensive steps, and the Quick Start should be for the Project Astra service overall?

**Comment by netapp-bcammett** [comment]
Hi Phoebe! Great job at Insight this week!

I understand the confusion and will make some changes to clear this up.

Thanks,
Ben
