### ISSUE TITLE
Google cloud > Add Service Account | Documentation is different to instructions in product

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/project-astra#29]
When I'm following the Project Astra "Add Compute" instructions, it gives me the instructions to use google-cloud-sdk and command line to add the service account 
<img width="938" alt="Screen Shot 2020-10-28 at 12 02 39 pm" src="https://user-images.githubusercontent.com/2746488/97464319-26c02180-1917-11eb-8a60-67a6188c5276.png">

whereas the documentation just links me to how to create a service account page on google cloud docs (https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account)

If we could have both options in the documentation, that would be the best outcome (IMO) and if not, docs should at least be consistent with the product instructions. I think the instructions inside the product are currently clearer than the docs.

**Comment by netapp-bcammett** [comment]
Phoebe,

I think this one is similar to the API issue: the quick start should really have an internal hyperlink to the section on the page that has more details.
