### ISSUE TITLE
API list incomplete and missing steps to enable

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/project-astra#30]
Page: [Set up Google Cloud](https://docs.netapp.com/us-en/project-astra/get-started/set-up-google-cloud.html)

I would like the steps here to actually enable the APIs - it's easier to do it this way than via the GUI individually...
```
gcloud services enable container.googleapis.com
gcloud services enable storage-component.googleapis.com
gcloud services enable storage-api.googleapis.com
gcloud services enable serviceusage.googleapis.com
gcloud services enable cloudresourcemanager.googleapis.com
gcloud services enable cloudvolumesgcp-api.netapp.com [I don't know what you need to actually enable this if not purchased]
gcloud services enable servicenetworking.googleapis.com
gcloud services enable servicemanagement.googleapis.com
```
(And I suppose it would make sense to include the --project= selector too in the event that it's not already set.)

The list is also missing serviceconsumermanagement.googleapis.com
<img width="953" alt="Screen Shot 2020-10-28 at 1 02 36 pm" src="https://user-images.githubusercontent.com/2746488/97474121-211c0900-1922-11eb-883e-5672035e28cd.png">

**Comment by phoebegoh** [comment]
To be more precise, perhaps I should be pointing out that we need internal hyperlinks vs the ones that just punt straight to the Google Cloud docs. (Since they have more detail if you scroll down, which I didn't until after posting).

I do think one of those APIs is missing, though (service consumer management API).

**Comment by netapp-bcammett** [comment]
Phoebe,

Makes sense and thanks for pointing out the missing API.

One follow up: it definitely seems easier to use gcloud than to individually select each API from the GUI. Do you think this audience is more likely to use gcloud (or another interface) than the GUI?

Thanks as always.

**Comment by phoebegoh** [comment]
I definitely know I prefer using the gcloud cli/sdk or using cloud shell, but I don't know how representative of the audience I might be. Also: I liked the videos in the content for the GUI, but I wouldn't watch a video that ran through CLI.

I think bringing it to the attention of product management would be good.
